@base = http://localhost:8080/v1

@depKey = 7c9e6679-7425-40de-944b-e07fc1f90ae8

### 1. создать счёт
# @name acc
POST {{base}}/accounts

### 2. депозит 500
# @name dep
POST {{base}}/accounts/{{"acc.response.body.id"}}/deposit
Idempotency-Key: {{$guid}}
Content-Type: application/json

{"amount": 500}

### 3. ретрай депозита 
POST {{base}}/accounts/{{acc.response.body.id}}/deposit
Idempotency-Key: {{depKey}}
Content-Type: application/json

{"amount": 500}

### 4. снятие 200
POST {{base}}/accounts/{{acc.response.body.id}}/withdraw
Idempotency-Key: {{$guid}}
Content-Type: application/json

{"amount": 200}

### 5. снятие больше баланса 
POST {{base}}/accounts/{{acc.response.body.id}}/withdraw
Idempotency-Key: {{$guid}}
Content-Type: application/json

{"amount": 100000}

### 6. битый JSON → 400
POST {{base}}/accounts/{{acc.response.body.id}}/deposit
Idempotency-Key: {{$guid}}
Content-Type: application/json

{"amount": "оопс"}

### 7. проверить баланс
GET {{base}}/accounts/{{acc.response.body.id}}

### Transfer
### создать счёт A
# @name accA
POST {{base}}/accounts

### создать счёт B
# @name accB
POST {{base}}/accounts

### пополнить A на 1000
POST {{base}}/accounts/{{accA.response.body.id}}/deposit
Idempotency-Key: {{$guid}}
Content-Type: application/json

{"amount": 1000}

### перевод A → B на 500
POST {{base}}/accounts/transfers
Idempotency-Key: {{$guid}}
Content-Type: application/json

{
  "from": "{{accA.response.body.id}}",
  "to": "{{accB.response.body.id}}",
  "amount": 500
}

###
GET {{base}}/accounts/{{accA.response.body.id}}

### история, страница 1
# @name hist1
GET {{base}}/accounts/{{accA.response.body.id}}/history?limit=3

### история, страница 2 — курсор из ответа страницы 1
GET {{base}}/accounts/{{accA.response.body.id}}/history?limit=20&cursor={{hist1.response.body.next_cursor}}
